version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: keep-db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    command: 
      - --auth
    volumes:
      - .docker/db_data:/data/db
